### ISSUE TITLE
YAML & JSON Single Profile

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#833]
Related to #749 we want to consider if a single profile would be YAML or JSON or both.  To be transparent, my preference is probably "both".  

There are endless debates on YAML vs JSON, and I don't think we should rehash that here.  Ultimately it seems to be a choice based on preference. 

There are specific issues around our circumstances: mainframe users learning VS Code & Zowe Explorer if we choose to support only yaml:

- VS Code & Microsoft seem to have selected (JSON w/comments - json5 / jsonc) for VS Code settings (`settings.json`, `launch.json` for configuration) - will we cause some confusion forcing exposure to two configuration file types?
- If we adopt a JSON schema standard, like JSON schema 7 - it works with both JSON and YAML, but it requires a separate extension from RedHat.  Will we leave some users in the dark if they forget / miss to install this extra extension and try to edit our config by hand?  

@phaumer perhaps you can comment on other considerations for our situation. 

Anecdotally, the RedHat YAML "appears" to have intellisense limitations compared to JSON.  Two examples (we could show others):

- It seems like you get prompted for all allowable values in JSON but not in YAML:
![image](https://user-images.githubusercontent.com/14940561/94925547-636e3980-048d-11eb-9d51-ef7f6630a745.png)

- It seems like you get examples when you type a field followed by a colon, e.g. `host:` with JSON but not in YAML:
![image](https://user-images.githubusercontent.com/14940561/94925639-8ac50680-048d-11eb-96c2-e01126ab2032.png)

Presumably the RedHat extension will be refined in time; however, it has lagged behind the JSON experience to date.  It might also cause limited usage of the JSON schema specification itself since it appears the YAML extension only supports a subset of what is possible. 

To try this yourself for evaluation, [here](https://github.com/zowe/zowe-cli/blob/single-profile-schema/schemas/zowe-base.schema.json) is a sample schema proposal.  

You can test this schema in json AND yaml with these in your `settings.json`:
```json5
    "json.schemas": [
        {
            "fileMatch": [
                "/.zowe/*.json"
            ],
            "url": "/schemas/zowe-base.schema.json"
        }
    ],
    // needs RedHat Extension
    "yaml.schemas": {
        "./schemas/zowe-base.schema.json": ["/.zowe/*.yaml"]
    }
```

YAML example:
```yaml
---
# comments supported
- default:
    host: "some.host.com"
    services:
        - zosmf:
            - tso1:
                host:
                
```

JSON example:
```json5
// comments supported
[{
    "default": {
        "host": "some.host.com",
        "services": [{
            "zosmf": [{
                "tso1": {
                    ""
                }
            }]
        }]
    }
}]
```

**Comment by phaumer** [comment]
The current schema works also with the Red Hat YAML LSP. If there are problems on Windows I recommend try relative vs absolute vs file url in the settings. For example, until 0.11.1 the absolute path was broken for Windows.

**Comment by phaumer** [comment]
Instead of doing an array of objects that can be names by the user, did you consider designing the schema more like a form to make it easer for the user to enter it and to better provide code completion? With the current schema there is no code completion until the user realized that they have to create an array and a named object themselves. If you organize it more like the example below the entire process of entering a file could be driven by code completion. It is also consistent with the way you see yaml being used by many cloud frameworks such as devfiles and plugin files in Che:

```yaml
name: zowe profiles
schemaVersion: 1.0

profiles: 
  - name: default
    host: some.host.com
    user: ibmuser
    services:
      - type: zosmf
        profiles:
          - name: tso1 
            port: 443
          - name: ca11
            port: 444
            rejectUnauthorized: false
```
