### ISSUE TITLE
Default value for response Timeour should not be null 

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#871]
The default value for responseTimeout should not be null if I chose to leave it out. I was expectin that the default value for a number should be a valid number as well.

```
type: number
            responseTimeout:
                type: number
                optionDefinition:
                    name: responseTimeout
                    aliases:
                        - rto
                    description: 'The maximum amount of time in ....
                    type: number
                    defaultValue: null
                    numericValueRange:
                        - 5
                        - 600
```
